name: CI
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DOCKER_REPO: larskghf
  DOCKER_IMAGE_NAME: template.py

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Generate changelog and create release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          changelog-generator-opt: "emojis=true"
          force-bump-patch-version: true
      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: larskghf
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.get-latest-tag.outputs.tag }}
            ${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:latest