name: CI
on:
  push:
    branches: [ "master" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPO: larskghf
  DOCKER_IMAGE_NAME: template.py
  DOCKER_IMAGE_TAG: latest

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Generate changelog and create release
        uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          changelog-generator-opt: "emojis=true"
        env:
          DOCKER_IMAGE_TAG: ${{ github.event.release.tag_name }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
            ${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE_NAME }}:latest